name: planningcenter_api
description: |
  Planning Center is an online platform for church management.

  This package gives you full coverage of the Planning Center API as described here:

  `https://developer.planning.center/docs/#/overview`


version: 0.8.0
repository: https://github.com/jeffmikels/planningcenter_api_dart
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.2 <3.0.0'


dependencies:
  http: ^0.13.3

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
