name: planningcenter_api
description: Supports nearly 100% of the Planning Center public API.
version: 0.1.3
repository: https://github.com/jeffmikels/planningcenter_api_dart
# homepage: https://www.example.com

# remove appid and secret from test before publishing
# publish_to: none

environment:
  sdk: '>=2.14.2 <3.0.0'


dependencies:
  http: ^0.13.3

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
