name: planningcenter_api
description: |
  This package gives you full coverage of the PlanningCenter API as described here:
  `https://developer.planning.center/docs/#/overview`

version: 0.8.1
repository: https://github.com/jeffmikels/planningcenter_api_dart
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.2 <3.0.0'


dependencies:
  http: ^0.13.3

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
